### ISSUE TITLE
KeyError: <orm.Database object at 0x01E5F830>

### ISSUE THREAD

**Issue by eaxdev** [fernandojunior/python-sqlite-orm#13]
Please help me, what am I doing wrong. I follow a `Readme.md`. I creadted model:

```
from orm import Model

class Post(Model):
    text = str

    def __init__(self, text):
        self.text = text
```

And I create some `main.py`. I try use orm:

```
from orm import Database
from post import Post

if __name__ == '__main__':
    db = Database('db.sqlite')
    Post.db = db
    post = Post('Hello').save()
    print(post.id)

```

But I have error:
```
D:\Projects\PycharmProjects\SQLite-ORM\venv\Scripts\python.exe D:/Projects/PycharmProjects/SQLite-ORM/main.py
Traceback (most recent call last):
  File "D:/Projects/PycharmProjects/SQLite-ORM/main.py", line 7, in <module>
    post = Post('Hello').save()
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 160, in save
    return self.__class__.manager(type_check=type_check).save(self)
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 174, in manager
    return Manager(db if db else cls.db, cls, type_check)
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 85, in __init__
    self.db.executescript(render_create_table_stmt(self.model))
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 37, in render_create_table_stmt
    column_definitions = ', '.join(render_column_definitions(model))
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 31, in render_column_definitions
    return ['%s %s' % (k, DATA_TYPES[v]) for k, v in attrs(model).items()]
  File "D:\Projects\PycharmProjects\SQLite-ORM\orm.py", line 31, in <listcomp>
    return ['%s %s' % (k, DATA_TYPES[v]) for k, v in attrs(model).items()]
KeyError: <orm.Database object at 0x01E5F830>
```

I realized that the error is due to the Python in the line `attrs(model).items()` returns the `db` field from the parent class.

What's wrong, How to fix it?

**Comment by fernandojunior** [comment]
Hi @romask17 

Thanks for reporting.
I fixed the problem in the PR #14 
Could you please test again?
